### ISSUE TITLE
Piped log program failed unexpectedly when using sed with Apache at windows

### ISSUE THREAD

**Issue by singhvikram704** [agordon/sed#1]
Here are the details :

[https://stackoverflow.com/questions/53118038/piped-log-program-failed-unexpectedly-when-using-sed-with-apache-at-windows](url)

**Comment by agordon** [comment]
Hello,

The github repository is a read-only mirror. I've forwarded your bug report to the gnu bug-tracker, and will answer there.
   http://bugs.gnu.org/33292
You can reply or add details by emailing 33292@debbugs.gnu.org .
